channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=24.0
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.13.0
name: mlflow-env
