name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test Global Variable
      run: echo "$DOCKER_HUB_TOKEN"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hoangsonhub/ddmsmse_ddm501
    - name: Login the Docker
      run: docker login -u "hoangsonhub" -p "dckr_pat_SPTpVXQoVlELrnQbLDxStBmBcmU"
    - name: Push the image Docker
      run: docker push hoangsonhub/ddmsmse_ddm501
